[project]
name = "hello_httpy"
version = "0.0.1"
description = ""
authors = [
    {name = "Thihan Soe",email = "thihansoe912@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic (>=2.12.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "hello_httpy.main:main"